### ISSUE TITLE
How to unlink/remove node?

### ISSUE THREAD

**Issue by NoICE** [lestrrat/go-libxml2#11]
Hello, I'm currently using your parser and I need to remove one element from the document.
I couldn't find a way how to do it. Browsing your code, I couldn't find any reference to http://xmlsoft.org/html/libxml-tree.html#xmlUnlinkNode (if that's the right function for it).

If you already have a way for removing nodes, how can it be done?

**Comment by lestrrat** [comment]
First off, sorry for the warnocking, I completely missed reports from this repository :/

To the main point, I think I missed to implement `RemoveChild`, and it's now on my TODO list...

**Comment by NoICE** [comment]
Thank you :-)
