### ISSUE TITLE
Parse HTML get attributes

### ISSUE THREAD

**Issue by fortrieb** [lestrrat/go-libxml2#15]
Hi,
i'm look for a way to get attribute/ parameter from a html node. As described in #4 get nodes with `nodes := xpath.NodeList(node.Find("/your/xpath"))` but i can't find any way to get parameter form these nodes.

I can parse `node.String()` to get parameter but is there something i have missed to get it directly?

Thanks

**Comment by lestrrat** [comment]
`"github.com/lestrrat/go-libxml2".Element.GetAttribute()` ?

**Comment by fortrieb** [comment]
I noticed the [Element.GetAttribute](https://godoc.org/github.com/lestrrat/go-libxml2/types#Element) method, but [type.Node](https://godoc.org/github.com/lestrrat/go-libxml2/types#Node) does not have any Element. How can is solve something like this:

`nodes := xpath.NodeList(node.Find("/your/xpath"))
param := nodes[0].GetAttribute()
`

**Comment by lestrrat** [comment]
`Node` is an `interface`. `interface` can be type asserted/converted. This is a basic Go operation.

**Comment by fortrieb** [comment]
Thanks, now i got and sorry i'm still new to golang programming.

**Comment by lestrrat** [comment]
may the force be with you :darth_vader:  :)
