### ISSUE TITLE
Memory leak!

### ISSUE THREAD

**Issue by gofmt** [lestrrat/go-libxml2#20]
Very serious

**Comment by lestrrat** [comment]
I'm open to the suggestion that there are problems, but would you care to elaborate, where, how to reproduce, etc?

**Comment by gofmt** [comment]
I am sorry, my English is not good.

**Comment by lestrrat** [comment]
@gofmt please show me the code then. I cannot do anything until you show me *something*

**Comment by lestrrat** [comment]
Please re-open this issue with concrete examples when you get around to it.
