### ISSUE TITLE
dom.WrapNode does not implement Comment case

### ISSUE THREAD

**Issue by shahan312** [lestrrat/go-libxml2#28]
Currently the `WrapNode` function does not implement the `clib.Comment` case. Is that on purpose or can I submit a PR for it?

**Comment by lestrrat** [comment]
PR with a test case is best :D

**Comment by shahan312** [comment]
Any recommendations on how to test `WrapNode`. I'm not sure on how to create the input (`n uintptr`)

**Comment by shahan312** [comment]
To add to previous comment, okay to use https://github.com/lestrrat/go-libxml2/pull/9/files as an example?

**Comment by lestrrat** [comment]
I'm guessing you have some code that doesn't compile or causes a runtime panic/error, so a test that reproduces that is fine. :)
