### ISSUE TITLE
OS X latest Xcode - fatal error: 'libxml/HTMLparser.h' file not found

### ISSUE THREAD

**Issue by edwinmoss** [lestrrat/go-libxml2#48]
Thank you so much for this package!

I am getting:

# github.com/lestrrat/go-libxml2/clib
../github.com/lestrrat/go-libxml2/clib/clib.go:28:10: fatal error: 'libxml/HTMLparser.h' file not found
#include <libxml/HTMLparser.h>

on the latest Xcode 9.2
Max OS X 10.13.3

I don't get the error on Xcode 8.2.1
Max OS X 10.13.3

Any ideas?

**Comment by lestrrat** [comment]
no idea. I have 9.2 and have no problems :/

**Comment by edwinmoss** [comment]
After some digging I discovered I hadn't installed all of Xcode - the command line stuff

xcode-select --install

Fixed it.

Thanks
