### ISSUE TITLE
cannot use nptr.children

### ISSUE THREAD

**Issue by wxf4150** [lestrrat/go-libxml2#6]
```
# github.com/lestrrat/go-libxml2/clib
../github.com/lestrrat/go-libxml2/clib/clib.go:1034: cannot use nptr.children (type *_Ctype_struct__xmlNode) as type *_Ctype_xmlNode in function argument
../github.com/lestrrat/go-libxml2/clib/clib.go:1037: cannot use _Cfunc_xmlNewText(cvalue) (type C.xmlNodePtr) as type *_Ctype_struct__xmlNode in assignment
../github.com/lestrrat/go-libxml2/clib/clib.go:1038: cannot use nptr (type *_Ctype_xmlNode) as type *_Ctype_struct__xmlNode in assignment
../github.com/lestrrat/go-libxml2/clib/clib.go:1062: cannot use nptr.doc (type *_Ctype_struct__xmlDoc) as type *_Ctype_xmlDoc in function argument
../github.com/lestrrat/go-libxml2/clib/clib.go:1065: cannot use nptr.doc (type *_Ctype_struct__xmlDoc) as type *_Ctype_xmlDoc in function argument
../github.com/lestrrat/go-libxml2/clib/clib.go:1083: cannot use nptr.doc (type *_Ctype_struct__xmlDoc) as type *_Ctype_xmlDoc in function argument
../github.com/lestrrat/go-libxml2/clib/clib.go:1103: cannot use nptr.doc (type *_Ctype_struct__xmlDoc) as type *_Ctype_xmlDoc in function argument
../github.com/lestrrat/go-libxml2/clib/clib.go:1502: cannot use ns.next (type *_Ctype_struct__xmlNs) as type *_Ctype_xmlNs in assignment
../github.com/lestrrat/go-libxml2/clib/clib.go:1526: cannot use nsdef.next (type *_Ctype_struct__xmlNs) as type *_Ctype_xmlNs in assignment
../github.com/lestrrat/go-libxml2/clib/clib.go:1552: cannot use nptr.doc (type *_Ctype_struct__xmlDoc) as type *_Ctype_xmlDoc in function argument
```

ubuntu 14.04  .  
i have installed libxml2
~$ pkg-config --cflags --libs libxml-2.0
~$  -I/usr/include/libxml2  -lxml2

**Comment by lestrrat** [comment]
Hmm, strange. @wxf4150  Can you please provide
1. the exact version of the installed libxml2
2. the exact version of go used

**Comment by wxf4150** [comment]
ubuntu 14.04  apt-cache privde libxml2 with versions:
2.9.1+dfsg1-3ubuntu4.6 - 
2.9.1+dfsg1-3ubuntu4 - 

i have another ubuntu 15.04 work well  with go-libxml2  use   libxml-2.9.2 

i think the new version libxml2 with version 2.9.2 will work.
i try to complie the new libxml2 version under ubuntu 14.04

**Comment by lestrrat** [comment]
And exact go version?

**Comment by wxf4150** [comment]
ubuntu 14.04 apt-get provide only  go1.2  ; or  i used go1.2

i willl upgrade ubuntu later!

**Comment by lestrrat** [comment]
I have a feeling go1.2 is the culprit. note that I have only been testing with go 1.5

**Comment by wxf4150** [comment]
i repaire my ubuntu 14.04  .   and complied the newest version  libxml2.9.3
with i use  the go 1.2 with libxml2.9.3  then error still , and the same.


when i install go 1.4.2,  with the  libxml2.9.3 , error bellow:
$ go get github.com/lestrrat/go-libxml2
# github.com/lestrrat/go-libxml2/clib
/usr/bin/ld: skipping incompatible /usr/local/lib/libxml2.so when searching for -lxml2
/usr/bin/ld: skipping incompatible /usr/local/lib/libxml2.a when searching for -lxml2
/usr/bin/ld: skipping incompatible //usr/local/lib/libxml2.so when searching for -lxml2
/usr/bin/ld: skipping incompatible //usr/local/lib/libxml2.a when searching for -lxml2

maybe go1.2 is to old .     and  libxml2.9.3 is to new.
i will complie  libxml2.9.2  for test  later.

**Comment by wxf4150** [comment]
wxf@wxf-pc:~/go/src$ go get github.com/lestrrat/go-libxml2
#github.com/lestrrat/go-libxml2/clib
/usr/bin/ld: skipping incompatible /usr/local/lib/libxml2.so when searching for -lxml2
/usr/bin/ld: skipping incompatible /usr/local/lib/libxml2.a when searching for -lxml2
/usr/bin/ld: skipping incompatible //usr/local/lib/libxml2.so when searching for -lxml2
/usr/bin/ld: skipping incompatible //usr/local/lib/libxml2.a when searching for -lxml2
/usr/bin/ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
wxf@wxf-pc:~/go/src$ ll /usr/local/lib/libxml2.so
lrwxrwxrwx 1 root root 16 12月 25 02:28 /usr/local/lib/libxml2.so -> libxml2.so.2.9.2*
wxf@wxf-pc:~/go/src$ go version
go version go1.4.2 linux/386


ubuntu14.04   go1.4.2   with libxml2.9.2   not work.
but i use other ubuntu 15.10 with system  defaut go and libxml work well.

**Comment by wxf4150** [comment]
i tested!  ubuntu 14.04 with go 1.5.1 work well with  go-libxml2.    

i found a new project go libxml2 project.
what do you think about  https://github.com/moovweb/gokogiri ?

**Comment by lestrrat** [comment]
That library won't work with other libraries that want to consume libxml2 (like [go-xmlsec](https://github.com/lestrrat/go-xmlsec)), so it won't work for me.
