### ISSUE TITLE
Literal() method will return" unknown node" with style tag

### ISSUE THREAD

**Issue by wxf4150** [lestrrat/go-libxml2#7]
nodes, err := doc.Find(xpath) ///html/body/div/div
	if err != nil {
		panic("failed to evaluate xpath: " + err.Error())
	}
	nlist:=nodes.NodeList()
	if len(nlist)>0{
		v,err:=nodes.NodeList().Literal()
		if err!=nil{
			fmt.Println("Literal:",err)
		}else{
			*str=v
		}
	}

i get  the error "Literal: unknown node".
when use NodeList().NodeValue   or NodeList().String()  will retrun the xml not the html  content.

is this a bug?

ubuntu 15.10 go1.5.2 libxml2.9.2

**Comment by lestrrat** [comment]
Hey, I'm really grateful that you are trying out this module, but when reporting code issues, please include a reproducible test case, otherwise I can only guess what you are talking about. 

I tried interpreting your issue and created a test case, but couldn't find any problems.
https://github.com/lestrrat/go-libxml2/commit/c9934099e727241f39da286beb849bac0596864e
https://travis-ci.org/lestrrat/go-libxml2/builds/98852151

**Comment by wxf4150** [comment]
sorry,it's my mistake:  string() NodeValue() return the right things.
i am new with git .  i am not good at travis-ci.org; and i will for a study

please with bellow html for test. the  Literal() method will return" unknown node"
html:=`<!DOCTYPE html>
<html>
<body>
<div>
<style>
</style>
	1234
</div>
</body>
</html>`
xpath:=`./body/div`

 when  there is no crlf between style tag, Literal will work.

**Comment by lestrrat** [comment]
@wxf4150 time to learn some more git: You should check out my branch (issues/7), and run your test against that. If you can confirm that it works, I will merge #9, and all should be okay.

**Comment by wxf4150** [comment]
git clone -b issues/7 git@github.com:lestrrat/go-libxml2.git test1
$ go test
--- FAIL: TestRegressionGH7 (0.00s)
        Error Trace:    xml_test.go:137
	Error:		Received unexpected error "unknown node"
	Messages:	Literal() should succeed
		
FAIL
exit status 1

**Comment by lestrrat** [comment]
I used your exact command line, and it works:

```
shoebill% git clone -b issues/7 git@github.com:lestrrat/go-libxml2.git test1
shoebill% go test .
ok  	github.com/lestrrat/test1	0.035s
```

And for the record:

```
shoebill% git log -n 1
commit 40611ff615253eed7bf1fecbc9133907e23706e1
Author: Daisuke Maki <lestrrat+github@gmail.com>
Date:   Tue Dec 29 16:46:48 2015 +0900

    Fix CDATA handling in Literal
```

**Comment by wxf4150** [comment]
oh!  sorry .  i  forgot copy   the "test1" folder  to  $GOPATH/src/github.com/lestrrat/go-libxml2;  my test referenced the old go-libxml2.

now it worked!

**Comment by lestrrat** [comment]
cool. In the future, please keep issues like this opened. When I merge the PR, Github will automatically change the status of an issue, and it's easier to see that things have been fixed that way.
